apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  namespace: {{ .Values.common.namespace }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.todoapp.secrets.SECRET_KEY }}
{{- range $k, $v := .Values.todoapp.secrets.db }}
  {{ $k }}: {{ $v | b64enc | quote }}
{{- end }}
